const div = dom.create(`<div id='testParent'><span>4</span></div>`)
// const node1 = dom.after(test, div)
// const node2 = dom.before(test, div)
const node3 = dom.append(test, div)
// dom.wrap(test, div)

// dom.removed(test)
// // const node4 = dom.empty(test)
// dom.attr(test, 'title', 'hi')
// const title = dom.attr(test, 'title')
// console.log(title)
// dom.text(div, '新的内容')
// dom.html(div, `<p>111111</p>`)
// dom.style(div, { border: '1px solid red', 'font-size': '12px' })
// const text = dom.style(div, 'font-size')
// console.log(text)
// dom.class.add(div, 'test')
// dom.class.remove(div, 'test')
// console.log(dom.class.has(div, 'test'))
// const fn = () => {
//     console.log('点击了')
// }
// dom.on(test, 'click', fn)
// dom.off(test, 'click', fn)
// const testDiv = dom.find('#parentDiv')
// console.log(dom.find('#test', testDiv))
// console.log(dom.parent(testParent))
// console.log(dom.siblings(test))
// console.log(dom.next(test))
// console.log(dom.previous(test))
// const t = dom.find('#parentDiv')
// dom.each(dom.children(t), (n) => dom.style(n, 'color', 'red'))
console.log(dom.index(test))